export enum Routes {
  Login = '/login',
  SignUp = '/create-account',
  Admin = '/admin',
  Dashboard = '/admin/dashboard',
  Customers = '/admin/customers',
  CustomersCreate = '/admin/customers/create',
  CustomersEdit = '/admin/customers/:id/edit',
  CustomersView = '/admin/customers/:id/view',
  Items = '/admin/items',
  ItemsCreate = '/admin/items/create',
  Estimates = '/admin/estimates',
  EstimatesCreate = '/admin/estimates/create',
  EstimatesEdit = '/admin/estimates/:id/edit',
  EstimatesView = '/admin/estimates/:id/view',
  InvoicesList = '/admin/invoices',
  InvoicesCreate = '/admin/invoices/create',
  InvoicesEdit = '/admin/invoices/:id/edit',
  InvoicesView = '/admin/invoices/:id/view',
  Payments = '/admin/payments',
  PaymentsCreate = '/admin/payments/create',
  Expenses = '/admin/expenses',
  ExpensesCreate = '/admin/expenses/create',
  Reports = '/admin/reports',
  Settings = '/admin/settings',
}
